### ISSUE TITLE
Intermittent NullReferenceException when accessing BusinessNoteStore

### ISSUE THREAD

**Issue by Thomas-Fleming** [evernote/evernote-cloud-sdk-windows#27]
I have a service that polls the Evernote every few minutes for updates to a users account. I'm getting an intermittent NullReferenceException on the following line of code:

``` csharp
ENSessionAdvanced.SharedSession.BusinessNoteStore;
```

StackTrace:

   at EvernoteSDK.ENSession.get_IsBusinessUser()
   at EvernoteSDK.ENSession.get_BusinessNoteStore()
   at EvernoteSDK.Advanced.ENSessionAdvanced.get_BusinessNoteStore()

Catching the exception and trying again soon after seems to continue fine.

**Comment by Thomas-Fleming** [comment]
Update: This appears to happen under 3 scenarios:
1. The user has exceeded their maximum number of hourly API calls
2. The developer token is invalid
3. Unknown - possibly the business token (the one valid for an hour) has expired and the client tries to access the API before renewing it?
